/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using NUnit.Framework;
using QuantConnect.Securities.FutureOption;

namespace QuantConnect.Tests.Common.Securities.FutureOption
{
    /// <summary>
    /// Fork-only golden tests (fop-weeklies P3): the registry-dispatched
    /// <see cref="FuturesOptionsUnderlyingMapper.GetUnderlyingFutureFromFutureOption"/> must
    /// reproduce the pre-P3 implementation byte-identically for every registry root whose
    /// underlyingRuleId is "legacy" (all upstream monthly/quarterly roots).
    /// The snapshot TestData/fop_legacy_underlying_golden_2012_2026.csv was generated by running
    /// the pre-P3 implementation (fork commit 340d483dd) over contract months 2012-01 through
    /// 2026-12: for each root the option expiration was derived through
    /// <see cref="FuturesOptionsExpiryFunctions.FuturesOptionExpiry"/> and the mapper was invoked
    /// with lookup date = expiration date. RTO (RTY options) is excluded: it declares expiry rule
    /// "legacy" but has no legacy expiry-table entry, so expiry derivation throws for it both
    /// before and after P3 (pre-existing P2 behavior, unrelated to the underlying mapper)
    /// </summary>
    [TestFixture, Category("FopFork")]
    public class FuturesOptionsUnderlyingGoldenTests
    {
        private const string GoldenFile = "TestData/fop_legacy_underlying_golden_2012_2026.csv";

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            // other fixtures mutate the in-memory market hours database (e.g. the upstream
            // ExpiryFunctionsReturnExpectedResultWhenExpiryIsAHoliday replaces the CME 6A entry),
            // which shifts holiday-adjusted expiries; reload from disk so the comparison runs
            // against the same calendar the snapshot was generated with
            QuantConnect.Securities.MarketHoursDatabase.Reset();
        }

        [Test]
        public void LegacyRootUnderlyingsAreByteIdenticalWithPreP3Snapshot()
        {
            var lines = File.ReadAllLines(GoldenFile);
            Assert.Greater(lines.Length, 8000, "golden snapshot appears truncated");

            var mismatches = new StringBuilder();
            var mismatchCount = 0;
            var count = 0;

            // skip header: option_root,market,future_ticker,contract_month,option_expiration,underlying_expiry
            foreach (var line in lines.Skip(1))
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                var parts = line.Split(',');
                var optionRoot = parts[0];
                var market = parts[1];
                var futureTicker = parts[2];
                var expiration = DateTime.ParseExact(parts[4], "yyyyMMdd HH:mm:ss", CultureInfo.InvariantCulture);
                var expectedUnderlyingExpiry = parts[5] == "null"
                    ? (DateTime?)null
                    : DateTime.ParseExact(parts[5], "yyyyMMdd HH:mm:ss", CultureInfo.InvariantCulture);

                var underlying = FuturesOptionsUnderlyingMapper.GetUnderlyingFutureFromFutureOption(
                    optionRoot, market, expiration, expiration.Date);
                count++;

                var matches = expectedUnderlyingExpiry == null
                    ? underlying == null
                    : underlying != null
                        && underlying.ID.Date == expectedUnderlyingExpiry.Value
                        && underlying.ID.Symbol == futureTicker;
                if (!matches)
                {
                    mismatchCount++;
                    if (mismatchCount <= 25)
                    {
                        mismatches.AppendLine(CultureInfo.InvariantCulture,
                            $"{optionRoot} ({market}) {parts[3]}: expected {parts[5]}, got " +
                            $"{(underlying == null ? "null" : $"{underlying.ID.Symbol} {underlying.ID.Date:yyyyMMdd HH:mm:ss}")}");
                    }
                }
            }

            Assert.AreEqual(8640, count, "unexpected golden row count");
            Assert.AreEqual(0, mismatchCount, $"golden mismatches:{Environment.NewLine}{mismatches}");
        }
    }
}
