/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using NUnit.Framework;
using QuantConnect.Securities.FutureOption;

namespace QuantConnect.Tests.Common.Securities.FutureOption.Expiry
{
    /// <summary>
    /// Fork-only golden tests (fop-weeklies): the P2 registry-routed
    /// <see cref="FuturesOptionsExpiryFunctions.FuturesOptionExpiry"/> must reproduce the pre-P2
    /// implementation byte-identically for every root the legacy hardcoded expiry table covers,
    /// and for the nine roots that historically resolved through the silent fallback to the
    /// underlying future's expiry (now declared explicitly as expiryRuleId "underlying_future").
    /// The snapshot TestData/fop_legacy_expiry_golden_2012_2026.csv was generated by running the
    /// pre-P2 implementation (fork commit fa0723d2e) over contract months 2012-01 through 2026-12
    /// </summary>
    [TestFixture, Category("FopFork")]
    public class FuturesOptionsExpiryGoldenTests
    {
        private const string GoldenFile = "TestData/fop_legacy_expiry_golden_2012_2026.csv";

        [Test]
        public void LegacyRootExpiriesAreByteIdenticalWithPreP2Snapshot()
        {
            var lines = File.ReadAllLines(GoldenFile);
            Assert.Greater(lines.Length, 8000, "golden snapshot appears truncated");

            var canonicalCache = new Dictionary<string, Symbol>();
            var mismatches = new StringBuilder();
            var mismatchCount = 0;
            var count = 0;

            // skip header: future_ticker,market,option_root,contract_month,expiry
            foreach (var line in lines.Skip(1))
            {
                if (string.IsNullOrWhiteSpace(line))
                {
                    continue;
                }

                var parts = line.Split(',');
                var futureTicker = parts[0];
                var market = parts[1];
                var contractMonth = DateTime.ParseExact(parts[3], "yyyyMM", CultureInfo.InvariantCulture);
                var expected = DateTime.ParseExact(parts[4], "yyyyMMdd HH:mm:ss", CultureInfo.InvariantCulture);

                var cacheKey = $"{market}-{futureTicker}";
                if (!canonicalCache.TryGetValue(cacheKey, out var canonicalOption))
                {
                    var future = Symbol.Create(futureTicker, SecurityType.Future, market);
                    canonicalOption = Symbol.CreateCanonicalOption(future);
                    canonicalCache[cacheKey] = canonicalOption;
                }

                var actual = FuturesOptionsExpiryFunctions.FuturesOptionExpiry(canonicalOption, contractMonth);
                count++;

                if (actual != expected)
                {
                    mismatchCount++;
                    if (mismatchCount <= 25)
                    {
                        mismatches.AppendLine(CultureInfo.InvariantCulture,
                            $"{futureTicker} ({market}) {parts[3]}: expected {expected:yyyy-MM-dd HH:mm:ss}, got {actual:yyyy-MM-dd HH:mm:ss}");
                    }
                }
            }

            Assert.AreEqual(8460, count, "unexpected golden row count");
            Assert.AreEqual(0, mismatchCount, $"golden mismatches:{Environment.NewLine}{mismatches}");
        }
    }
}
