/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

using System;
using System.Linq;
using NUnit.Framework;
using QuantConnect.Lean.Engine.DataFeeds;
using QuantConnect.Securities.FutureOption;
using QuantConnect.Tests.Common.Securities.FutureOption;

namespace QuantConnect.Tests.Engine.DataFeeds
{
    /// <summary>
    /// fop-weeklies fork P4: future option chain fan-out across registry roots in the backtesting
    /// chain provider, exercised against the fabricated point-in-time weekly universe fixtures
    /// generated by <see cref="FutureOptionUniverseTestDataGenerator"/>
    /// </summary>
    [TestFixture, NonParallelizable, Category("FopFork")]
    public class BacktestingOptionChainProviderFanOutTests
    {
        private BacktestingOptionChainProvider _provider;

        private static Symbol EsMarch2020 => FutureOptionUniverseTestDataGenerator.UnderlyingFuture;

        [OneTimeSetUp]
        public void OneTimeSetUp()
        {
            _provider = new BacktestingOptionChainProvider();
            _provider.Initialize(new(TestGlobals.MapFileProvider, TestGlobals.HistoryProvider));
        }

        [SetUp]
        public void SetUp()
        {
            FutureOptionChainCycleSettings.Reset();
        }

        [OneTimeTearDown]
        public void OneTimeTearDown()
        {
            FutureOptionChainCycleSettings.Reset();
            FutureOptionsRootRegistry.Reset();
        }

        [Test]
        public void DefaultMaskIsLegacyIdentical()
        {
            // no registration: default cycle mask is Standard, which must serve only the standard
            // root with the exact same contracts as the pre-fork provider (the upstream
            // BacktestingOptionChainProviderLoadsFutureOptionChain expectation)
            var esOptionChain = _provider.GetOptionContractList(
                Symbol.CreateFuture(QuantConnect.Securities.Futures.Indices.SP500EMini, Market.CME, new DateTime(2020, 6, 19)),
                new DateTime(2020, 1, 5))
                .ToList();

            Assert.AreEqual(107, esOptionChain.Count);
            Assert.IsTrue(esOptionChain.All(symbol => symbol.ID.Symbol == "ES"));
            Assert.AreEqual(2900m, esOptionChain.Min(s => s.ID.StrikePrice));
            Assert.AreEqual(3500m, esOptionChain.Max(s => s.ID.StrikePrice));
        }

        [Test]
        public void FanOutUnionsMonthlyAndWeeklyChains()
        {
            FutureOptionChainCycleSettings.Register("ES", Market.CME,
                FutureOptionExpiryCycles.Standard | FutureOptionExpiryCycles.Weekly);

            var chain = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 7)).ToList();
            var roots = chain.Select(symbol => symbol.ID.Symbol).ToHashSet();

            // standard monthly root from the repository sample data
            Assert.Contains("ES", roots.ToList());
            // fabricated weekly roots
            Assert.Contains("EW2", roots.ToList());
            Assert.Contains("EW3", roots.ToList());

            // every contract keeps the requested underlying and is a future option
            Assert.IsTrue(chain.All(symbol => symbol.SecurityType == SecurityType.FutureOption));
            Assert.IsTrue(chain.All(symbol => symbol.Underlying == EsMarch2020));

            // weekly expiries resolved from the fabricated files
            Assert.AreEqual(new DateTime(2020, 1, 10), chain.Where(s => s.ID.Symbol == "EW2").Select(s => s.ID.Date).Distinct().Single());
            Assert.AreEqual(new DateTime(2020, 1, 17), chain.Where(s => s.ID.Symbol == "EW3").Select(s => s.ID.Date).Distinct().Single());

            // E1A expired on 2020-01-06, so its contracts must not survive the expiry filter on the 7th
            Assert.IsFalse(roots.Contains("E1A"));
        }

        [Test]
        public void WeeklyRootsAreNotServedUnderTheStandardMask()
        {
            // Standard-only mask: the weekly universe files exist but must not be read
            var chain = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 7)).ToList();
            var roots = chain.Select(symbol => symbol.ID.Symbol).ToHashSet();

            Assert.AreEqual(new[] { "ES" }, roots.ToArray());
        }

        [Test]
        public void ExpiredWeeklyRootStillServedOnItsExpiryDate()
        {
            FutureOptionChainCycleSettings.Register("ES", Market.CME,
                FutureOptionExpiryCycles.Standard | FutureOptionExpiryCycles.Weekly);

            // E1A expires 2020-01-06: on its expiry date it is still part of the chain
            var chain = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 6)).ToList();

            var e1aContracts = chain.Where(symbol => symbol.ID.Symbol == "E1A").ToList();
            Assert.IsNotEmpty(e1aContracts);
            Assert.AreEqual(new DateTime(2020, 1, 6), e1aContracts.Select(s => s.ID.Date).Distinct().Single());
        }

        [Test]
        public void PointInTimeListingGating()
        {
            FutureOptionChainCycleSettings.Register("ES", Market.CME,
                FutureOptionExpiryCycles.Standard | FutureOptionExpiryCycles.Weekly);

            // Universe files follow LEAN's daily convention: the file of trading date D is the chain
            // known at the start of D+1. EW3's first universe file is 2020-01-06 (listing realism),
            // so its contracts must first appear on 2020-01-07 and never before, while EW2 (files
            // from 2020-01-02) is already present
            var chainBeforeListing = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 6)).ToList();
            var rootsBeforeListing = chainBeforeListing.Select(symbol => symbol.ID.Symbol).ToHashSet();
            Assert.IsTrue(rootsBeforeListing.Contains("EW2"));
            Assert.IsFalse(rootsBeforeListing.Contains("EW3"));

            var chainAfterListing = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 7)).ToList();
            Assert.IsTrue(chainAfterListing.Any(symbol => symbol.ID.Symbol == "EW3"));
        }

        [Test]
        public void ListedSinceGatesRootsWithDataBeforeTheirLaunch()
        {
            FutureOptionChainCycleSettings.Register("ES", Market.CME, FutureOptionExpiryCycles.All);

            // E1B universe files exist for 2020-01-07 but the root's registry ListedSince is
            // 2022-04-01 (Tuesday weeklies launched April 2022): the chain must skip the root
            var chain = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 7)).ToList();
            Assert.IsFalse(chain.Any(symbol => symbol.ID.Symbol == "E1B"));

            // explicit targeting is gated too
            var e1bCanonical = Symbol.CreateCanonicalOption(EsMarch2020, "E1B", Market.CME, null);
            Assert.IsEmpty(_provider.GetOptionContractList(e1bCanonical, new DateTime(2020, 1, 7)));
        }

        [Test]
        public void ExplicitRootTargetingReturnsSingleRoot()
        {
            // targeting a specific weekly root serves only that root, without any registration
            var ew2Canonical = Symbol.CreateCanonicalOption(EsMarch2020, "EW2", Market.CME, null);
            var chain = _provider.GetOptionContractList(ew2Canonical, new DateTime(2020, 1, 7)).ToList();

            Assert.IsNotEmpty(chain);
            Assert.IsTrue(chain.All(symbol => symbol.ID.Symbol == "EW2"));
            Assert.IsTrue(chain.All(symbol => symbol.Underlying == EsMarch2020));
        }

        [Test]
        public void RootFilterRestrictsFanOut()
        {
            FutureOptionChainCycleSettings.Register("ES", Market.CME,
                FutureOptionExpiryCycles.Standard | FutureOptionExpiryCycles.Weekly, new[] { "ES", "EW3" });

            var chain = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 7)).ToList();
            var roots = chain.Select(symbol => symbol.ID.Symbol).ToHashSet();

            Assert.IsTrue(roots.Contains("ES"));
            Assert.IsTrue(roots.Contains("EW3"));
            Assert.IsFalse(roots.Contains("EW2"));
        }

        [Test]
        public void DailyCycleRootDoesNotServeStaleUniverses()
        {
            try
            {
                InjectSyntheticDailyRoot();

                var dailyCanonical = Symbol.CreateCanonicalOption(EsMarch2020,
                    FutureOptionUniverseTestDataGenerator.DailyTestRoot, Market.CME, null);
                var weeklyCanonical = Symbol.CreateCanonicalOption(EsMarch2020, "EW3", Market.CME, null);

                // both roots have a 2020-01-08 universe file, which serves the chain of 2020-01-09
                // on time (LEAN's daily convention: the file of trading date D is the chain of D+1)
                Assert.IsNotEmpty(_provider.GetOptionContractList(dailyCanonical, new DateTime(2020, 1, 9)).ToList());
                Assert.IsNotEmpty(_provider.GetOptionContractList(weeklyCanonical, new DateTime(2020, 1, 9)).ToList());

                // 2020-01-10 has no on-time universe file (there is no 2020-01-09 file). The weekly
                // root falls back to the latest file within the last 3 trading days (its chain
                // composition is stable), but the daily root must not serve a stale chain: the
                // 2020-01-08 file is a different instrument set on the 10th (design B issue 8)
                Assert.IsNotEmpty(_provider.GetOptionContractList(weeklyCanonical, new DateTime(2020, 1, 10)).ToList());
                Assert.IsEmpty(_provider.GetOptionContractList(dailyCanonical, new DateTime(2020, 1, 10)).ToList());
            }
            finally
            {
                FutureOptionsRootRegistry.Reset();
            }
        }

        [Test]
        public void DailyCycleRootGatedInFanOutToo()
        {
            try
            {
                InjectSyntheticDailyRoot();
                FutureOptionChainCycleSettings.Register("ES", Market.CME, FutureOptionExpiryCycles.All);

                // fan-out on a date with an on-time universe file: the daily root contributes contracts
                var chainOnFileDate = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 9)).ToList();
                Assert.IsTrue(chainOnFileDate.Any(symbol =>
                    symbol.ID.Symbol == FutureOptionUniverseTestDataGenerator.DailyTestRoot));

                // fan-out on a date without an on-time universe file: weekly roots fall back, the daily root is gated
                var chainOnMissingDate = _provider.GetOptionContractList(EsMarch2020, new DateTime(2020, 1, 10)).ToList();
                Assert.IsTrue(chainOnMissingDate.Any(symbol => symbol.ID.Symbol == "EW3"));
                Assert.IsFalse(chainOnMissingDate.Any(symbol =>
                    symbol.ID.Symbol == FutureOptionUniverseTestDataGenerator.DailyTestRoot));
            }
            finally
            {
                FutureOptionsRootRegistry.Reset();
            }
        }

        /// <summary>
        /// Adds the synthetic ESD daily root of the fabricated fixtures to the registry definitions.
        /// There is no production daily-root seed yet (P5 work), so the gating tests inject one
        /// </summary>
        private static void InjectSyntheticDailyRoot()
        {
            var definitions = FutureOptionsRootRegistry.GetDefinitions().ToList();
            definitions.Add(new FutureOptionRootDefinition
            {
                FutureTicker = "ES",
                OptionTicker = FutureOptionUniverseTestDataGenerator.DailyTestRoot,
                Market = Market.CME,
                Cycle = FutureOptionExpiryCycles.Daily,
                ExpiryRuleId = "underlying_future",
                UnderlyingRuleId = "NextQuarterly",
                ListedSince = new DateTime(2019, 1, 1),
                Settlement = FutureOptionSettlement.FuturesSettled,
                Enabled = true
            });

            FutureOptionsRootRegistry.SetDefinitionsForTesting(definitions);
        }
    }
}
